name: Oak Park Antiques
favicon: null
layout_spectrum: 0.40037
typography_spectrum: 0.9363251782488078
title: Bricks purchased from the Frank Lloyd Wright Preservation Trust
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fcfcfc'
    - '#000110'
    - '#8c8b79'
    - '#615a3e'
    - '#b2b19f'
  brandStrength: 0.5
  lightness: 0.8125
  saturation: 0.375
  rhythmicContrast: 0.25
purpose: []
